version: '2'

services:
  tm-base:
    image: hundred666/tendermint:v0.27.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=tendermint_default
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - HOME=/tendermint
    working_dir: /tendermint